include theos/makefiles/common.mk

BUNDLE_NAME = iControlFlipswitch
iControlFlipswitch_FILES = Switch.x
iControlFlipswitch_FRAMEWORKS = UIKit
iControlFlipswitch_LIBRARIES = flipswitch
iControlFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk